### PR TITLE
1.20.4

### PR DESCRIPTION
**Pull request by FireInstall**
update dependencys, gradle and cape textures
Trying to fix issue #15 but could also still not fix it.
Didn't test the fix, since AE didn't have an version for 1.20.4 fabric ready

### CODE REVIEW

**Comment by ldanidev** [comment]
Right, thanks for submitting this PR. I'll see if i can test it asap.

**Comment by ldanidev** [comment]
Everything seems to work just fine. I was also not able to reproduce #18 so this probably fixes it.

**Comment by ldanidev** [comment]
Also, i think im going to stick with a default branch and  give support for the latest version.

**Comment by FireInstall** [comment]
Alright, this does make potential future PRs easier for me since I don't need to worry where the merge into for a new version.
Awesome, thanks for your work!

**Pull request merged**
